<?php
// This file is part of Moodle - http://moodle.org/

/**
 * Public-key encryption helpers for Face Attendance embedding payloads.
 *
 * Registered SFace embedding JSON is encrypted at rest with a libsodium sealed box.
 * Moodle stores only ciphertext. The matching camera station keeps the private key
 * and decrypts the payload after a successful HMAC-authenticated bootstrap request.
 *
 * @package     mod_faceattendance
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

define('FACEATTENDANCE_EMBEDDING_CRYPTO_VERSION', 1);
define('FACEATTENDANCE_EMBEDDING_CRYPTO_SCHEME', 'libsodium-sealed-box-x25519-xsalsa20poly1305');

function faceattendance_embedding_crypto_station_public_key(stdClass $faceattendance): string {
    return trim((string)($faceattendance->stationpublickey ?? ''));
}

function faceattendance_embedding_crypto_enabled(stdClass $faceattendance): bool {
    return faceattendance_embedding_crypto_station_public_key($faceattendance) !== '';
}

function faceattendance_embedding_crypto_decode_public_key(string $publickey): string {
    $publickey = trim($publickey);
    if ($publickey === '') {
        throw new moodle_exception('Missing station public key for embedding encryption.');
    }

    // Accept base64/raw public keys generated by generate_station_crypto_keys.py.
    $raw = base64_decode($publickey, true);
    if ($raw === false) {
        // Also accept URL-safe base64 without padding for easier copy/paste.
        $normalized = strtr($publickey, '-_', '+/');
        $normalized .= str_repeat('=', (4 - strlen($normalized) % 4) % 4);
        $raw = base64_decode($normalized, true);
    }

    if ($raw === false || strlen($raw) !== SODIUM_CRYPTO_BOX_PUBLICKEYBYTES) {
        throw new moodle_exception('Invalid station public key. Expected a base64 encoded libsodium/X25519 public key of 32 bytes.');
    }

    return $raw;
}

function faceattendance_embedding_crypto_key_id_from_raw_public_key(string $rawpublickey): string {
    return hash('sha256', $rawpublickey);
}

function faceattendance_embedding_is_encrypted_payload($payload): bool {
    if (is_string($payload)) {
        $payload = json_decode($payload, true);
    }
    return is_array($payload)
        && !empty($payload['faceattendanceEncryptedEmbedding'])
        && (($payload['scheme'] ?? '') === FACEATTENDANCE_EMBEDDING_CRYPTO_SCHEME)
        && !empty($payload['ciphertext']);
}

function faceattendance_embedding_encrypt_json_for_station(string $rawjson, stdClass $faceattendance, int $courseid, int $userid): string {
    if (!faceattendance_embedding_crypto_enabled($faceattendance)) {
        return $rawjson;
    }

    if (!function_exists('sodium_crypto_box_seal')) {
        throw new moodle_exception('The PHP sodium extension is required for station-only embedding encryption.');
    }

    $rawpublickey = faceattendance_embedding_crypto_decode_public_key(faceattendance_embedding_crypto_station_public_key($faceattendance));
    $ciphertext = sodium_crypto_box_seal($rawjson, $rawpublickey);
    if ($ciphertext === false || $ciphertext === '') {
        throw new moodle_exception('Could not encrypt the embedding payload for the configured station public key.');
    }

    $envelope = [
        'faceattendanceEncryptedEmbedding' => true,
        'version' => FACEATTENDANCE_EMBEDDING_CRYPTO_VERSION,
        'scheme' => FACEATTENDANCE_EMBEDDING_CRYPTO_SCHEME,
        'stationKeyId' => faceattendance_embedding_crypto_key_id_from_raw_public_key($rawpublickey),
        'course' => $courseid,
        'userid' => $userid,
        'ciphertext' => base64_encode($ciphertext),
        'createdAt' => time(),
    ];

    return json_encode($envelope, JSON_UNESCAPED_SLASHES);
}
